[package]
name = "jadr_chess_web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.1"
uuid = {version="0.8.2", features = ["v4"]}
ws = "0.9.2"
json = "0.12.4"